#!/bin/bash

# Complete competency descriptors update script
# MW Panel 2.0 - July 2025

echo "🔄 Inserting remaining competency descriptors..."

# STEM Descriptors for PRIMARIA
echo "📚 Inserting STEM descriptors for PRIMARIA..."
docker-compose exec -T postgres psql -U mwpanel -d mwpanel -c "INSERT INTO operative_descriptors (id, code, description, \"shortDescription\", \"order\", \"competencyId\", \"exitProfileId\") VALUES
  (gen_random_uuid(), 'STEM1', 'Utiliza, de manera guiada, algunos métodos inductivos y deductivos propios del razonamiento matemático en situaciones conocidas, y selecciona y emplea algunas estrategias para resolver problemas reflexionando sobre las soluciones obtenidas.', 'Utiliza métodos de razonamiento matemático para resolver problemas.', 1, '33333333-3333-3333-3333-333333333333', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'STEM2', 'Utiliza el pensamiento científico para entender y explicar algunos de los fenómenos que ocurren a su alrededor, confiando en el conocimiento como motor de desarrollo, utilizando herramientas e instrumentos adecuados, planteándose preguntas y realizando experimentos sencillos de forma guiada.', 'Utiliza el pensamiento científico para entender fenómenos cotidianos.', 2, '33333333-3333-3333-3333-333333333333', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'STEM3', 'Realiza, de forma guiada, proyectos, diseñando, fabricando y evaluando diferentes prototipos o modelos, adaptándose ante la incertidumbre, para generar en equipo un producto creativo con un objetivo concreto, procurando la participación de todo el grupo y resolviendo pacíficamente los conflictos que puedan surgir.', 'Realiza proyectos tecnológicos diseñando y evaluando prototipos.', 3, '33333333-3333-3333-3333-333333333333', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'STEM4', 'Interpreta y transmite los elementos más relevantes de algunos métodos y resultados científicos, matemáticos y tecnológicos de forma clara y veraz, utilizando la terminología científica apropiada, en diferentes formatos (dibujos, diagramas, gráficos, símbolos...) y aprovechando de forma crítica, ética y responsable la cultura digital para compartir y construir nuevos conocimientos.', 'Interpreta y transmite resultados científicos usando terminología apropiada.', 4, '33333333-3333-3333-3333-333333333333', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'STEM5', 'Participa en acciones fundamentadas científicamente para promover la salud y preservar el medio ambiente y los seres vivos, aplicando principios de ética y seguridad y practicando el consumo responsable.', 'Participa en acciones para promover la salud y preservar el medio ambiente.', 5, '33333333-3333-3333-3333-333333333333', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb');"

# STEM Descriptors for SECUNDARIA
echo "🔬 Inserting STEM descriptors for SECUNDARIA..."
docker-compose exec -T postgres psql -U mwpanel -d mwpanel -c "INSERT INTO operative_descriptors (id, code, description, \"shortDescription\", \"order\", \"competencyId\", \"exitProfileId\") VALUES
  (gen_random_uuid(), 'STEM1', 'Utiliza métodos inductivos y deductivos propios del razonamiento matemático en situaciones conocidas, y selecciona y emplea diferentes estrategias para resolver problemas analizando críticamente las soluciones y reformulando el procedimiento, si fuera necesario.', 'Utiliza métodos de razonamiento matemático analizando críticamente las soluciones.', 1, '33333333-3333-3333-3333-333333333333', '325ae957-d0c8-48e4-83ac-202bbcf0202e'),
  (gen_random_uuid(), 'STEM2', 'Utiliza el pensamiento científico para entender y explicar los fenómenos que ocurren a su alrededor, confiando en el conocimiento como motor de desarrollo, planteándose preguntas y comprobando hipótesis mediante la experimentación y la indagación, utilizando herramientas e instrumentos adecuados, apreciando la importancia de la precisión y la veracidad y mostrando una actitud crítica acerca del alcance y las limitaciones de la ciencia.', 'Utiliza el pensamiento científico mediante experimentación e indagación.', 2, '33333333-3333-3333-3333-333333333333', '325ae957-d0c8-48e4-83ac-202bbcf0202e'),
  (gen_random_uuid(), 'STEM3', 'Plantea y desarrolla proyectos diseñando, fabricando y evaluando diferentes prototipos o modelos para generar o utilizar productos que den solución a una necesidad o problema de forma creativa y en equipo, procurando la participación de todo el grupo, resolviendo pacíficamente los conflictos que puedan surgir, adaptándose ante la incertidumbre y valorando la importancia de la sostenibilidad.', 'Desarrolla proyectos tecnológicos creativos valorando la sostenibilidad.', 3, '33333333-3333-3333-3333-333333333333', '325ae957-d0c8-48e4-83ac-202bbcf0202e'),
  (gen_random_uuid(), 'STEM4', 'Interpreta y transmite los elementos más relevantes de procesos, razonamientos, demostraciones, métodos y resultados científicos, matemáticos y tecnológicos de forma clara y precisa y en diferentes formatos (gráficos, tablas, diagramas, fórmulas, esquemas, símbolos...), aprovechando de forma crítica la cultura digital e incluyendo el lenguaje matemático-formal con ética y responsabilidad, para compartir y construir nuevos conocimientos.', 'Interpreta y transmite resultados científicos con lenguaje matemático-formal.', 4, '33333333-3333-3333-3333-333333333333', '325ae957-d0c8-48e4-83ac-202bbcf0202e'),
  (gen_random_uuid(), 'STEM5', 'Emprende acciones fundamentadas científicamente para promover la salud física, mental y social, y preservar el medio ambiente y los seres vivos; y aplica principios de ética y seguridad en la realización de proyectos para transformar su entorno próximo de forma sostenible, valorando su impacto global y practicando el consumo responsable.', 'Emprende acciones para promover la salud y transformar el entorno sosteniblemente.', 5, '33333333-3333-3333-3333-333333333333', '325ae957-d0c8-48e4-83ac-202bbcf0202e');"

echo "✅ STEM descriptors inserted successfully!"

# CD Descriptors for PRIMARIA
echo "💻 Inserting CD descriptors for PRIMARIA..."
docker-compose exec -T postgres psql -U mwpanel -d mwpanel -c "INSERT INTO operative_descriptors (id, code, description, \"shortDescription\", \"order\", \"competencyId\", \"exitProfileId\") VALUES
  (gen_random_uuid(), 'CD1', 'Realiza búsquedas guiadas en internet y hace uso de estrategias sencillas para el tratamiento digital de la información (palabras clave, selección de información relevante, organización de datos...) con una actitud crítica sobre los contenidos obtenidos.', 'Realiza búsquedas guiadas en internet con actitud crítica.', 1, '44444444-4444-4444-4444-444444444444', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'CD2', 'Crea, integra y reelabora contenidos digitales en distintos formatos (texto, tabla, imagen, audio, vídeo, programa informático...) mediante el uso de diferentes herramientas digitales para expresar ideas, sentimientos y conocimientos, respetando la propiedad intelectual y los derechos de autor de los contenidos que reutiliza.', 'Crea contenidos digitales en diversos formatos respetando la propiedad intelectual.', 2, '44444444-4444-4444-4444-444444444444', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'CD3', 'Participa en actividades o proyectos escolares mediante el uso de herramientas o plataformas virtuales para construir nuevo conocimiento, comunicarse, trabajar cooperativamente, y compartir datos y contenidos en entornos digitales restringidos y supervisados de manera segura, con una actitud abierta y responsable ante su uso.', 'Participa en proyectos escolares usando herramientas digitales de forma segura.', 3, '44444444-4444-4444-4444-444444444444', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'CD4', 'Conoce los riesgos y adopta, con la orientación del docente, medidas preventivas al usar las tecnologías digitales para proteger los dispositivos, los datos personales, la salud y el medioambiente, y se inicia en la adopción de hábitos de uso crítico, seguro, saludable y sostenible de dichas tecnologías.', 'Adopta medidas preventivas para un uso seguro de las tecnologías digitales.', 4, '44444444-4444-4444-4444-444444444444', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb'),
  (gen_random_uuid(), 'CD5', 'Se inicia en el desarrollo de soluciones digitales sencillas y sostenibles (reutilización de materiales tecnológicos, programación informática por bloques, robótica educativa...) para resolver problemas concretos o retos propuestos de manera creativa, solicitando ayuda en caso necesario.', 'Desarrolla soluciones digitales sencillas para resolver problemas.', 5, '44444444-4444-4444-4444-444444444444', 'bacc1ecc-7232-4a2e-96aa-127054e3cebb');"

echo "✅ CD descriptors for PRIMARIA inserted successfully!"

echo "🎯 Competency descriptors update completed!"