import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';
import { StudentNote } from './student-note.entity';
import { SharedNoteComment } from './shared-note-comment.entity';
import { User } from '../../users/entities/user.entity';

export enum ModerationReason {
  INAPPROPRIATE_CONTENT = 'inappropriate_content',
  SPAM = 'spam',
  HARASSMENT = 'harassment',
  VIOLENCE = 'violence',
  ADULT_CONTENT = 'adult_content',
  COPYRIGHT = 'copyright',
  FAKE_NEWS = 'fake_news',
  OTHER = 'other'
}

export enum ModerationStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  FLAGGED = 'flagged'
}

export enum ModerationAction {
  FLAG = 'flag',
  APPROVE = 'approve',
  REJECT = 'reject',
  DELETE = 'delete',
  WARN_USER = 'warn_user'
}

@Entity('moderation_reports')
@Index(['status', 'createdAt'])
@Index(['noteId', 'status'])
@Index(['moderatorId'])
export class ModerationReport {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Relación con la nota reportada
  @Column({ name: 'noteId' })
  noteId: string;

  @ManyToOne(() => StudentNote, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'noteId' })
  note: StudentNote;

  // Relación opcional con comentario reportado (para reportes de comentarios específicos)
  @Column({ name: 'commentId', nullable: true })
  commentId: string;

  @ManyToOne(() => SharedNoteComment, { onDelete: 'CASCADE', nullable: true })
  @JoinColumn({ name: 'commentId' })
  comment: SharedNoteComment;

  // Usuario que reporta (puede ser null para reportes anónimos)
  @Column({ name: 'reportedById', nullable: true })
  reportedById: string;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'reportedById' })
  reportedBy: User;

  // Moderador asignado
  @Column({ name: 'moderatorId', nullable: true })
  moderatorId: string;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'moderatorId' })
  moderator: User;

  @Column({
    type: 'enum',
    enum: ModerationReason,
  })
  reason: ModerationReason;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Column({
    type: 'enum',
    enum: ModerationStatus,
    default: ModerationStatus.PENDING,
  })
  status: ModerationStatus;

  @Column({
    type: 'enum',
    enum: ModerationAction,
    nullable: true,
  })
  action: ModerationAction;

  @Column({ type: 'text', nullable: true })
  moderatorComments: string;

  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, any>;

  @Column({ type: 'boolean', default: false })
  autoGenerated: boolean;

  @Column({ type: 'integer', default: 1 })
  priority: number; // 1 = alta, 5 = baja

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: 'timestamp', nullable: true })
  resolvedAt: Date;
}