import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateModerationSystem1755868200000 implements MigrationInterface {
    name = 'CreateModerationSystem1755868200000';

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Crear tabla de configuración de moderación
        await queryRunner.query(`
            CREATE TABLE "moderation_config" (
                "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
                "autoModerationEnabled" boolean NOT NULL DEFAULT false,
                "bannedWords" jsonb NOT NULL DEFAULT '[]',
                "suspiciousPhrases" jsonb NOT NULL DEFAULT '[]',
                "sensitivity" integer NOT NULL DEFAULT 5,
                "autoApproveTrustedUsers" boolean NOT NULL DEFAULT false,
                "trustedUserIds" jsonb NOT NULL DEFAULT '[]',
                "whitelistedDomains" jsonb NOT NULL DEFAULT '[]',
                "notifyModeratorsOnReport" boolean NOT NULL DEFAULT true,
                "notifyUsersOnAction" boolean NOT NULL DEFAULT false,
                "maxModerationHours" integer NOT NULL DEFAULT 24,
                "emailNotificationSettings" jsonb,
                "autoModerationRules" jsonb,
                "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
                "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
                CONSTRAINT "PK_moderation_config" PRIMARY KEY ("id")
            )
        `);

        // Crear tipos enum para moderación
        await queryRunner.query(`
            CREATE TYPE "public"."moderation_reports_reason_enum" AS ENUM(
                'inappropriate_content',
                'spam',
                'harassment',
                'violence',
                'adult_content',
                'copyright',
                'fake_news',
                'other'
            )
        `);

        await queryRunner.query(`
            CREATE TYPE "public"."moderation_reports_status_enum" AS ENUM(
                'pending',
                'approved',
                'rejected',
                'flagged'
            )
        `);

        await queryRunner.query(`
            CREATE TYPE "public"."moderation_reports_action_enum" AS ENUM(
                'flag',
                'approve',
                'reject',
                'delete',
                'warn_user'
            )
        `);

        // Crear tabla de reportes de moderación
        await queryRunner.query(`
            CREATE TABLE "moderation_reports" (
                "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
                "noteId" uuid NOT NULL,
                "reportedById" uuid,
                "moderatorId" uuid,
                "reason" "public"."moderation_reports_reason_enum" NOT NULL,
                "description" text,
                "status" "public"."moderation_reports_status_enum" NOT NULL DEFAULT 'pending',
                "action" "public"."moderation_reports_action_enum",
                "moderatorComments" text,
                "metadata" jsonb,
                "autoGenerated" boolean NOT NULL DEFAULT false,
                "priority" integer NOT NULL DEFAULT 1,
                "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
                "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
                "resolvedAt" TIMESTAMP,
                CONSTRAINT "PK_moderation_reports" PRIMARY KEY ("id")
            )
        `);

        // Crear índices para optimizar consultas
        await queryRunner.query(`CREATE INDEX "IDX_moderation_reports_status_created" ON "moderation_reports" ("status", "createdAt")`);
        await queryRunner.query(`CREATE INDEX "IDX_moderation_reports_note_status" ON "moderation_reports" ("noteId", "status")`);
        await queryRunner.query(`CREATE INDEX "IDX_moderation_reports_moderator" ON "moderation_reports" ("moderatorId")`);
        await queryRunner.query(`CREATE INDEX "IDX_moderation_reports_priority" ON "moderation_reports" ("priority", "createdAt")`);

        // Crear claves foráneas
        await queryRunner.query(`
            ALTER TABLE "moderation_reports" 
            ADD CONSTRAINT "FK_moderation_reports_noteId" 
            FOREIGN KEY ("noteId") REFERENCES "student_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);

        await queryRunner.query(`
            ALTER TABLE "moderation_reports" 
            ADD CONSTRAINT "FK_moderation_reports_reportedById" 
            FOREIGN KEY ("reportedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION
        `);

        await queryRunner.query(`
            ALTER TABLE "moderation_reports" 
            ADD CONSTRAINT "FK_moderation_reports_moderatorId" 
            FOREIGN KEY ("moderatorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION
        `);

        // Insertar configuración por defecto
        await queryRunner.query(`
            INSERT INTO "moderation_config" 
            ("autoModerationEnabled", "bannedWords", "sensitivity", "autoApproveTrustedUsers", "trustedUserIds") 
            VALUES 
            (false, '["palabrota", "spam", "inapropiado"]', 5, false, '[]')
        `);

        console.log('✅ Migration CreateModerationSystem1755868200000 completed successfully');
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Eliminar claves foráneas
        await queryRunner.query(`ALTER TABLE "moderation_reports" DROP CONSTRAINT "FK_moderation_reports_moderatorId"`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" DROP CONSTRAINT "FK_moderation_reports_reportedById"`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" DROP CONSTRAINT "FK_moderation_reports_noteId"`);

        // Eliminar índices
        await queryRunner.query(`DROP INDEX "IDX_moderation_reports_priority"`);
        await queryRunner.query(`DROP INDEX "IDX_moderation_reports_moderator"`);
        await queryRunner.query(`DROP INDEX "IDX_moderation_reports_note_status"`);
        await queryRunner.query(`DROP INDEX "IDX_moderation_reports_status_created"`);

        // Eliminar tablas
        await queryRunner.query(`DROP TABLE "moderation_reports"`);
        await queryRunner.query(`DROP TABLE "moderation_config"`);

        // Eliminar tipos enum
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_reason_enum"`);

        console.log('✅ Migration CreateModerationSystem1755868200000 reverted successfully');
    }
}