import React, { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Typography,
  Button,
  Space,
  Tabs,
  Card,
  Table,
  Modal,
  message,
  Row,
  Col,
  Statistic,
  Select,
  Input,
  DatePicker,
  Tag,
  Popconfirm,
  Divider,
  Spin,
  Progress,
  Badge,
  Tooltip,
  Form,
  Checkbox,
  Alert,
  Slider,
  InputNumber,
} from 'antd';
import { Line, Column, Pie } from '@ant-design/plots';
import {
  BookOutlined,
  FileTextOutlined,
  SoundOutlined,
  PictureOutlined,
  UserOutlined,
  CalendarOutlined,
  EyeOutlined,
  DeleteOutlined,
  SettingOutlined,
  BarChartOutlined,
  HeartOutlined,
  ShareAltOutlined,
  PaperClipOutlined,
  DownloadOutlined,
  SyncOutlined,
  SecurityScanOutlined,
  WarningOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  FlagOutlined,
  MessageOutlined,
} from '@ant-design/icons';
import { motion } from 'framer-motion';
import dayjs from 'dayjs';
import jsPDF from 'jspdf';
import apiClient from '../../services/apiClient';
import { useAuth } from '../../hooks/useAuth';

const { Title, Text } = Typography;
const { TabPane } = Tabs;
const { RangePicker } = DatePicker;
const { Option } = Select;

interface AdminDashboardStats {
  overview: {
    totalNotes: number;
    totalUsers: number;
    activeNotesToday: number;
    notesWithAttachments: number;
    favoriteNotesCount: number;
    totalShared: number;
    activeShares: number;
    uniqueSharedWith: number;
  };
  notesByType: {
    [key: string]: number;
  };
  topUsers: Array<{
    userId: string;
    email: string;
    firstName?: string;
    lastName?: string;
    fullName?: string;
    noteCount: number;
  }>;
}

interface StudentNote {
  id: string;
  title: string;
  content: string;
  type: 'text' | 'voice' | 'drawing' | 'mixed';
  author: {
    id: string;
    email: string;
    profile?: {
      firstName?: string;
      lastName?: string;
    };
  };
  subject?: {
    id: string;
    name: string;
  };
  createdAt: string;
  updatedAt: string;
  viewCount: number;
  isFavorite: boolean;
  driveFileId?: string;
}

interface PaginatedNotes {
  data: StudentNote[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// Interfaces de Moderación
interface ModerationReport {
  id: string;
  noteId: string;
  commentId?: string; // Para reportes de comentarios específicos
  reportedById: string;
  moderatorId?: string;
  reason: 'inappropriate_content' | 'spam' | 'harassment' | 'violence' | 'adult_content' | 'copyright' | 'fake_news' | 'other';
  description?: string;
  status: 'pending' | 'approved' | 'rejected' | 'flagged';
  action?: 'flag' | 'approve' | 'reject' | 'delete' | 'warn_user';
  metadata: any;
  autoGenerated: boolean;
  priority: number;
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
  note: StudentNote;
  comment?: { // Comentario reportado (si es reporte de comentario)
    id: string;
    content: string;
    createdAt: string;
    user?: {
      id: string;
      email: string;
      profile?: {
        firstName?: string;
        lastName?: string;
      };
    };
  };
  reportedBy?: {
    id: string;
    email: string;
    profile?: {
      firstName?: string;
      lastName?: string;
    };
  };
  moderator?: {
    id: string;
    email: string;
    profile?: {
      firstName?: string;
      lastName?: string;
    };
  };
}

interface ModerationStats {
  totalReports: number;
  pendingReports: number;
  resolvedReports: number;
  averageResolutionTime: number;
  reportsByReason: { reason: string; count: number }[];
  reportsByStatus: { status: string; count: number }[];
  topReportedAuthors: { authorId: string; authorName: string; reportCount: number }[];
  moderatorActivity: { moderatorId: string; moderatorName: string; actionsCount: number }[];
}

interface ModerationConfig {
  id: string;
  autoModerationEnabled: boolean;
  bannedWords: string[];
  suspiciousPhrases: string[];
  sensitivity: number;
  autoApproveTrustedUsers: boolean;
  trustedUserIds: string[];
  whitelistedDomains: string[];
  notifyModeratorsOnReport: boolean;
  notifyUsersOnAction: boolean;
  maxModerationHours: number;
  emailNotificationSettings?: any;
  autoModerationRules?: any;
  createdAt: string;
  updatedAt: string;
}

interface PaginatedReports {
  data: ModerationReport[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// Funciones de exportación
const exportToCSV = (data: any[], filename: string) => {
  if (!data || data.length === 0) {
    message.warning('No hay datos para exportar');
    return;
  }

  const headers = Object.keys(data[0]).join(',');
  const csvContent = [
    headers,
    ...data.map(row => Object.values(row).map(value => `"${value}"`).join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}-${dayjs().format('YYYY-MM-DD')}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
};

const exportAnalyticsToPDF = (analyticsData: any, period: string) => {
  if (!analyticsData) {
    message.warning('No hay datos de analytics para exportar');
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // Header
  doc.setFontSize(20);
  doc.text('Reporte de Analytics - Apuntes de Estudiantes', 14, 20);
  
  doc.setFontSize(12);
  doc.text(`Período: ${period}`, 14, 30);
  doc.text(`Fecha de generación: ${dayjs().format('DD/MM/YYYY HH:mm')}`, 14, 40);
  
  // Línea separadora
  doc.line(14, 45, pageWidth - 14, 45);
  
  let yPosition = 55;
  
  // Estadísticas principales
  doc.setFontSize(16);
  doc.text('📊 Estadísticas Principales', 14, yPosition);
  yPosition += 10;
  
  doc.setFontSize(11);
  const stats = analyticsData.engagement;
  doc.text(`• Promedio de vistas: ${stats.averageViews}`, 20, yPosition);
  yPosition += 8;
  doc.text(`• Tasa de favoritos: ${stats.favoriteRate}%`, 20, yPosition);
  yPosition += 8;
  doc.text(`• Máximo de vistas: ${stats.maxViews}`, 20, yPosition);
  yPosition += 8;
  doc.text(`• Total de apuntes: ${stats.totalNotes}`, 20, yPosition);
  yPosition += 15;
  
  // Usuarios más productivos
  if (analyticsData.topUsers && analyticsData.topUsers.length > 0) {
    doc.setFontSize(16);
    doc.text('👥 Usuarios Más Productivos', 14, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    analyticsData.topUsers.slice(0, 10).forEach((user: any, index: number) => {
      doc.text(`${index + 1}. ${user.name}: ${user.noteCount} apuntes`, 20, yPosition);
      yPosition += 8;
    });
    yPosition += 10;
  }
  
  // Tipos de contenido
  if (analyticsData.contentTypes && analyticsData.contentTypes.length > 0) {
    doc.setFontSize(16);
    doc.text('📋 Distribución por Tipo de Contenido', 14, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    analyticsData.contentTypes.forEach((content: any) => {
      doc.text(`• ${content.type.toUpperCase()}: ${content.count} apuntes (${content.averageViews.toFixed(1)} vistas promedio)`, 20, yPosition);
      yPosition += 8;
    });
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.text('MW Panel 2.0 - Sistema de Gestión Educativa', 14, pageHeight - 10);
  
  doc.save(`analytics-apuntes-${period}-${dayjs().format('YYYY-MM-DD')}.pdf`);
};

const AdminStudentNotesPage: React.FC = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState<'overview' | 'notes' | 'analytics' | 'moderation' | 'settings'>('overview');
  const [selectedNote, setSelectedNote] = useState<StudentNote | null>(null);
  const [showNoteModal, setShowNoteModal] = useState(false);
  const [fileBlobUrls, setFileBlobUrls] = useState<Record<string, string>>({});
  const [notesFilters, setNotesFilters] = useState({
    page: 1,
    limit: 20,
    search: '',
    type: '',
    authorId: '',
    sortBy: 'createdAt',
    sortOrder: 'DESC' as 'ASC' | 'DESC',
  });
  const [systemSettings, setSystemSettings] = useState({
    maxFileSize: 20,
    allowedFileTypes: ['image/*', 'audio/*'],
    enableSharing: true,
    maxNotesPerUser: 1000,
    autoDeleteAfterDays: null,
    moderationEnabled: false,
  });

  // Estados de Moderación
  const [moderationFilters, setModerationFilters] = useState({
    page: 1,
    limit: 20,
    status: '',
    reason: '',
    moderatorId: '',
    dateFrom: '',
    dateTo: '',
  });
  const [selectedReport, setSelectedReport] = useState<ModerationReport | null>(null);
  const [showReportModal, setShowReportModal] = useState(false);
  const [showActionModal, setShowActionModal] = useState(false);
  const [showConfigModal, setShowConfigModal] = useState(false);
  const [azureStatus, setAzureStatus] = useState<{
    isConfigured: boolean;
    isWorking: boolean;
    lastTest?: Date;
    error?: string;
  } | null>(null);
  const [testingAzureConnection, setTestingAzureConnection] = useState(false);

  // Form hooks
  const [moderationForm] = Form.useForm();
  const [moderationConfigForm] = Form.useForm();

  // Helper functions
  const formatModerationReason = (reason: string): string => {
    const reasons: { [key: string]: string } = {
      inappropriate_content: 'Contenido inapropiado',
      spam: 'Spam',
      harassment: 'Acoso',
      violence: 'Violencia',
      adult_content: 'Contenido adulto',
      copyright: 'Derechos de autor',
      fake_news: 'Noticias falsas',
      other: 'Otro'
    };
    return reasons[reason] || reason;
  };

  // Fetch dashboard statistics
  const { data: dashboardStats, isLoading: statsLoading } = useQuery<AdminDashboardStats>({
    queryKey: ['admin-student-notes-dashboard'],
    queryFn: async () => {
      const response = await apiClient.get('/student-notes/admin/dashboard');
      return response.data;
    },
  });

  // Fetch all notes for admin
  const { data: notesData, isLoading: notesLoading } = useQuery<PaginatedNotes>({
    queryKey: ['admin-student-notes-all', notesFilters],
    queryFn: async () => {
      const params = new URLSearchParams();
      Object.entries(notesFilters).forEach(([key, value]) => {
        if (value) params.append(key, value.toString());
      });
      
      const response = await apiClient.get(`/student-notes/admin/all-notes?${params.toString()}`);
      return response.data;
    },
    enabled: activeTab === 'notes',
  });

  // Analytics period state
  const [analyticsPeriod, setAnalyticsPeriod] = useState<'week' | 'month' | 'year'>('month');

  // Fetch analytics
  const { data: analyticsData, isLoading: analyticsLoading } = useQuery({
    queryKey: ['admin-student-notes-analytics', analyticsPeriod],
    queryFn: async () => {
      const response = await apiClient.get(`/student-notes/admin/analytics?period=${analyticsPeriod}`);
      return response.data;
    },
    enabled: activeTab === 'analytics',
  });

  // Queries de Moderación
  const { data: moderationReports, isLoading: reportsLoading, refetch: refetchReports } = useQuery<PaginatedReports>({
    queryKey: ['admin-moderation-reports', moderationFilters],
    queryFn: async () => {
      const params = new URLSearchParams();
      Object.entries(moderationFilters).forEach(([key, value]) => {
        if (value) params.append(key, value.toString());
      });
      const response = await apiClient.get(`/student-notes/admin/moderation/reports?${params}`);
      return response.data.data;
    },
    enabled: activeTab === 'moderation',
  });

  const { data: moderationStats, isLoading: moderationStatsLoading } = useQuery<ModerationStats>({
    queryKey: ['admin-moderation-stats'],
    queryFn: async () => {
      const response = await apiClient.get('/student-notes/admin/moderation/stats');
      return response.data.data;
    },
    enabled: activeTab === 'moderation',
  });

  const { data: moderationConfig, isLoading: configLoading, refetch: refetchConfig } = useQuery<ModerationConfig>({
    queryKey: ['admin-moderation-config'],
    queryFn: async () => {
      const response = await apiClient.get('/student-notes/admin/moderation/config');
      return response.data.data;
    },
    enabled: activeTab === 'moderation',
  });

  // Force delete note mutation
  const forceDeleteNoteMutation = useMutation({
    mutationFn: async (noteId: string) => {
      await apiClient.delete(`/student-notes/admin/note/${noteId}/force`);
    },
    onSuccess: () => {
      message.success('Apunte eliminado exitosamente');
      queryClient.invalidateQueries({ queryKey: ['admin-student-notes-dashboard'] });
      queryClient.invalidateQueries({ queryKey: ['admin-student-notes-all'] });
      setShowNoteModal(false);
    },
    onError: (error: any) => {
      message.error(`Error al eliminar: ${error.response?.data?.message || error.message}`);
    },
  });

  // Update system settings mutation
  const updateSettingsMutation = useMutation({
    mutationFn: async (settings: any) => {
      const response = await apiClient.put('/student-notes/admin/settings', settings);
      return response.data;
    },
    onSuccess: () => {
      message.success('Configuración actualizada exitosamente');
    },
    onError: (error: any) => {
      message.error(`Error al actualizar configuración: ${error.response?.data?.message || error.message}`);
    },
  });

  // Mutaciones de Moderación
  const takeModerationActionMutation = useMutation({
    mutationFn: async ({ reportId, action, notifyAuthor }: {
      reportId: string;
      action: string;
      notifyAuthor?: boolean;
    }) => {
      const response = await apiClient.put(`/student-notes/admin/moderation/report/${reportId}/action`, {
        action,
        notifyAuthor,
      });
      return response.data;
    },
    onSuccess: () => {
      message.success('Acción de moderación aplicada exitosamente');
      queryClient.invalidateQueries({ queryKey: ['admin-moderation-reports'] });
      queryClient.invalidateQueries({ queryKey: ['admin-moderation-stats'] });
      setShowActionModal(false);
      setSelectedReport(null);
    },
    onError: (error: any) => {
      message.error(`Error al aplicar acción: ${error.response?.data?.message || error.message}`);
    },
  });

  const updateModerationConfigMutation = useMutation({
    mutationFn: async (config: Partial<ModerationConfig>) => {
      const response = await apiClient.put('/student-notes/admin/moderation/config', config);
      return response.data;
    },
    onSuccess: () => {
      message.success('Configuración de moderación actualizada exitosamente');
      refetchConfig();
      setShowConfigModal(false);
    },
    onError: (error: any) => {
      message.error(`Error al actualizar configuración: ${error.response?.data?.message || error.message}`);
    },
  });

  const scanContentMutation = useMutation({
    mutationFn: async () => {
      const response = await apiClient.post('/student-notes/admin/moderation/scan');
      return response.data;
    },
    onSuccess: (data) => {
      message.success(`Escaneo completado. Revisadas: ${data.data.scanned} notas, Flagged: ${data.data.flagged}`);
      refetchReports();
      queryClient.invalidateQueries({ queryKey: ['admin-moderation-stats'] });
    },
    onError: (error: any) => {
      message.error(`Error en escaneo: ${error.response?.data?.message || error.message}`);
    },
  });

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'text': return <FileTextOutlined />;
      case 'voice': return <SoundOutlined />;
      case 'drawing': return <PictureOutlined />;
      default: return <BookOutlined />;
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'text': return 'blue';
      case 'voice': return 'green';
      case 'drawing': return 'purple';
      default: return 'orange';
    }
  };

  const formatUserName = (author: StudentNote['author']) => {
    if (author.profile?.firstName && author.profile?.lastName) {
      return `${author.profile.firstName} ${author.profile.lastName}`;
    }
    return author.email;
  };

  const handleViewNote = (note: StudentNote) => {
    setSelectedNote(note);
    setShowNoteModal(true);
  };

  const handleDeleteNote = (noteId: string) => {
    forceDeleteNoteMutation.mutate(noteId);
  };

  // Funciones auxiliares para moderación
  const getReasonLabel = (reason: string) => {
    const labels = {
      inappropriate_content: 'Contenido Inapropiado',
      spam: 'Spam',
      harassment: 'Acoso',
      violence: 'Violencia',
      adult_content: 'Contenido Adulto',
      copyright: 'Derechos de Autor',
      fake_news: 'Noticias Falsas',
      other: 'Otro'
    };
    return labels[reason as keyof typeof labels] || reason;
  };

  const getStatusColor = (status: string) => {
    const colors = {
      pending: 'orange',
      approved: 'green',
      rejected: 'red',
      flagged: 'red'
    };
    return colors[status as keyof typeof colors] || 'default';
  };

  const getStatusIcon = (status: string) => {
    const icons = {
      pending: <WarningOutlined />,
      approved: <CheckCircleOutlined />,
      rejected: <CloseCircleOutlined />,
      flagged: <FlagOutlined />
    };
    return icons[status as keyof typeof icons] || <WarningOutlined />;
  };

  const getPriorityColor = (priority: number) => {
    if (priority <= 2) return 'red';
    if (priority <= 3) return 'orange';
    return 'green';
  };

  const handleViewReport = (report: ModerationReport) => {
    setSelectedReport(report);
    setShowReportModal(true);
  };

  const handleTakeAction = (report: ModerationReport) => {
    setSelectedReport(report);
    setShowActionModal(true);
  };

  const handleUpdateModerationFilters = (key: string, value: any) => {
    setModerationFilters(prev => ({
      ...prev,
      [key]: value,
      page: key === 'page' ? value : 1,
    }));
  };

  const handleUpdateFilters = (key: string, value: any) => {
    setNotesFilters(prev => ({
      ...prev,
      [key]: value,
      page: key !== 'page' ? 1 : value, // Reset to page 1 unless changing page
    }));
  };

  const handleSaveSettings = () => {
    updateSettingsMutation.mutate(systemSettings);
  };

  const handleModerationAction = async () => {
    try {
      if (!selectedReport) return;
      
      const values = await moderationForm.validateFields();
      await takeModerationActionMutation.mutateAsync({
        reportId: selectedReport.id,
        action: values.action,
      });
      
      setShowActionModal(false);
      moderationForm.resetFields();
    } catch (error) {
      console.error('Error applying moderation action:', error);
      // Error is already handled by the mutation
    }
  };

  const handleModerationConfigSave = async () => {
    try {
      const values = await moderationConfigForm.validateFields();
      await updateModerationConfigMutation.mutateAsync(values);
      
      setShowConfigModal(false);
    } catch (error) {
      console.error('Error saving moderation config:', error);
      // Error is already handled by the mutation
    }
  };

  const handleTestAzureConnection = async () => {
    setTestingAzureConnection(true);
    try {
      const response = await apiClient.get('/student-notes/admin/moderation/azure/status');
      if (response.data.success) {
        setAzureStatus(response.data.data);
        message.success(response.data.message);
      } else {
        message.error(response.data.message || 'Error al probar conexión con Azure');
      }
    } catch (error: any) {
      console.error('Error testing Azure connection:', error);
      message.error('Error al conectar con Azure AI Content Safety');
      setAzureStatus({
        isConfigured: false,
        isWorking: false,
        error: error.response?.data?.message || error.message || 'Error de conexión'
      });
    } finally {
      setTestingAzureConnection(false);
    }
  };

  const createAuthenticatedBlobUrl = async (noteId: string): Promise<{ url: string | null; contentType?: string; fileName?: string }> => {
    // Obtener token desde el localStorage de MW Panel
    const authData = localStorage.getItem('mw-panel-auth');
    let token = null;
    
    if (authData) {
      try {
        const parsedAuth = JSON.parse(authData);
        token = parsedAuth.state?.accessToken || parsedAuth.accessToken;
      } catch (error) {
        console.error('Error parsing auth data:', error);
      }
    }
    
    if (!token) {
      console.error('No access token available in mw-panel-auth');
      return { url: null };
    }
    
    try {
      console.log('🔄 Fetching authenticated file for note:', noteId);
      const response = await fetch(`https://plataforma.mundoworld.school/api/student-notes/${noteId}/stream`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      console.log('📄 Response status:', response.status, response.statusText);
      console.log('📄 Response headers:', {
        'content-type': response.headers.get('content-type'),
        'content-disposition': response.headers.get('content-disposition')
      });
      
      if (!response.ok) {
        console.error('❌ Error fetching file:', response.status, response.statusText);
        return { url: null };
      }
      
      const contentType = response.headers.get('content-type') || 'application/octet-stream';
      const contentDisposition = response.headers.get('content-disposition');
      const fileName = contentDisposition?.match(/filename="(.+)"/)?.[1] || undefined;
      
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      
      console.log('✅ Blob URL created successfully:', { url, contentType, fileName });
      return { url, contentType, fileName };
    } catch (error) {
      console.error('❌ Error creating blob URL:', error);
      return { url: null };
    }
  };

  // Componente para renderizar contenido multimedia autenticado
  const AuthenticatedMedia: React.FC<{ note: StudentNote; type: 'audio' | 'image' | 'presentation' }> = ({ note, type }) => {
    const [blobUrl, setBlobUrl] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(false);
    const [contentType, setContentType] = useState<string | null>(null);
    const [fileName, setFileName] = useState<string | null>(null);

    useEffect(() => {
      console.log('🎬 AuthenticatedMedia mounting for note:', { id: note.id, type, driveFileId: note.driveFileId });
      
      if (note.driveFileId) {
        createAuthenticatedBlobUrl(note.id)
          .then((result) => {
            console.log('🎬 AuthenticatedMedia result:', result);
            setBlobUrl(result.url);
            setContentType(result.contentType || null);
            setFileName(result.fileName || null);
            setLoading(false);
            setError(!result.url);
          })
          .catch((err) => {
            console.error('🎬 AuthenticatedMedia error:', err);
            setLoading(false);
            setError(true);
          });
      } else {
        console.warn('🎬 AuthenticatedMedia: No driveFileId for note:', note.id);
        setLoading(false);
        setError(true);
      }

      // Cleanup blob URL when component unmounts
      return () => {
        if (blobUrl) {
          URL.revokeObjectURL(blobUrl);
        }
      };
    }, [note.id, note.driveFileId]);

    if (loading) {
      return <div style={{ padding: 16, textAlign: 'center' }}>Cargando...</div>;
    }

    if (error || !blobUrl) {
      return (
        <div style={{ padding: 16, textAlign: 'center', color: '#999' }}>
          <div>Archivo no disponible</div>
          <div style={{ fontSize: '12px', marginTop: 4 }}>
            Debug: driveFileId={note.driveFileId ? 'presente' : 'ausente'}, 
            error={error ? 'sí' : 'no'}, 
            blobUrl={blobUrl ? 'presente' : 'ausente'}
          </div>
        </div>
      );
    }

    switch (type) {
      case 'audio':
        return (
          <div>
            <audio 
              controls 
              style={{ width: '100%', marginTop: 8 }}
              src={blobUrl}
            >
              Su navegador no soporta el elemento audio.
            </audio>
            {fileName && (
              <div style={{ fontSize: '12px', color: '#666', marginTop: 4 }}>
                📁 {fileName} ({contentType})
              </div>
            )}
          </div>
        );
      case 'image':
        return (
          <div>
            <img 
              src={blobUrl}
              alt={note.title}
              style={{ 
                maxWidth: '100%', 
                maxHeight: '300px', 
                marginTop: 8,
                border: '1px solid #d9d9d9',
                borderRadius: 4
              }}
              onError={() => setError(true)}
            />
            {fileName && (
              <div style={{ fontSize: '12px', color: '#666', marginTop: 4 }}>
                🖼️ {fileName} ({contentType})
              </div>
            )}
          </div>
        );
      case 'presentation':
        const isPdf = contentType?.includes('pdf');
        const isPowerPoint = contentType?.includes('powerpoint') || fileName?.includes('.ppt');
        const isJson = contentType?.includes('json');
        
        // Si es JSON, es probablemente contenido de presentación estructurado
        if (isJson && blobUrl) {
          return (
            <div>
              <Button 
                type="primary" 
                icon={<EyeOutlined />}
                onClick={async () => {
                  try {
                    const response = await fetch(blobUrl);
                    const jsonData = await response.json();
                    
                    // Mostrar JSON formateado en una nueva ventana
                    const newWindow = window.open('', '_blank');
                    if (newWindow) {
                      newWindow.document.write(`
                        <html>
                          <head><title>Presentación - ${fileName || 'Sin título'}</title></head>
                          <body style="font-family: Arial, sans-serif; padding: 20px;">
                            <h2>📊 Contenido de Presentación</h2>
                            <pre style="background: #f5f5f5; padding: 15px; border-radius: 5px; overflow: auto;">
                              ${JSON.stringify(jsonData, null, 2)}
                            </pre>
                          </body>
                        </html>
                      `);
                      newWindow.document.close();
                    }
                  } catch (error) {
                    console.error('Error al procesar presentación JSON:', error);
                    window.open(blobUrl, '_blank');
                  }
                }}
                style={{ marginRight: 8 }}
              >
                Ver Presentación (JSON)
              </Button>
              {fileName && (
                <div style={{ fontSize: '12px', color: '#666', marginTop: 4 }}>
                  📊 {fileName} ({contentType})
                </div>
              )}
            </div>
          );
        }
        
        return (
          <div>
            <Button 
              type="primary" 
              icon={<EyeOutlined />}
              onClick={() => window.open(blobUrl, '_blank')}
              style={{ marginRight: 8 }}
            >
              Ver {isPdf ? 'PDF' : isPowerPoint ? 'PowerPoint' : 'Presentación'}
            </Button>
            {fileName && (
              <div style={{ fontSize: '12px', color: '#666', marginTop: 4 }}>
                📊 {fileName} ({contentType})
              </div>
            )}
          </div>
        );
      default:
        return (
          <div style={{ padding: 16, color: '#999' }}>
            Tipo de archivo no soportado: {type}
          </div>
        );
    }
  };

  const renderNoteContent = (note: StudentNote) => {
    const baseStyle = {
      marginTop: 8,
      padding: 16,
      background: '#fafafa',
      borderRadius: 6,
      maxHeight: '400px',
      overflow: 'auto'
    };

    switch (note.type) {
      case 'voice':
        return (
          <div style={baseStyle}>
            <Text>🎵 Nota de voz</Text>
            <AuthenticatedMedia note={note} type="audio" />
            <div style={{ marginTop: 8, padding: 8, background: '#f0f0f0', borderRadius: 4 }}>
              <Text type="secondary">{note.content}</Text>
            </div>
          </div>
        );

      case 'drawing':
        return (
          <div style={baseStyle}>
            <Text>🎨 Dibujo/Imagen</Text>
            <AuthenticatedMedia note={note} type="image" />
            <div style={{ marginTop: 8, padding: 8, background: '#f0f0f0', borderRadius: 4 }}>
              <Text type="secondary">{note.content}</Text>
            </div>
          </div>
        );

      case 'presentation':
        // Función para renderizar presentación desde contenido JSON
        const renderPresentationContent = () => {
          if (note.driveFileId) {
            // Si tiene archivo en Drive, usar AuthenticatedMedia
            return <AuthenticatedMedia note={note} type="presentation" />;
          } else {
            // Si no tiene archivo en Drive, el contenido está en note.content
            try {
              const presentationData = JSON.parse(note.content);
              
              return (
                <div>
                  <Button 
                    type="primary" 
                    icon={<EyeOutlined />}
                    onClick={() => {
                      // Crear nueva ventana con presentación formateada
                      const newWindow = window.open('', '_blank');
                      if (newWindow) {
                        newWindow.document.write(`
                          <html>
                            <head>
                              <title>Presentación - ${presentationData.metadata?.title || 'Sin título'}</title>
                              <style>
                                body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
                                .slide { 
                                  background: white; 
                                  margin: 20px 0; 
                                  padding: 20px; 
                                  border-radius: 8px; 
                                  box-shadow: 0 2px 8px rgba(0,0,0,0.1); 
                                }
                                .slide-title { 
                                  font-size: 24px; 
                                  font-weight: bold; 
                                  color: #333; 
                                  margin-bottom: 10px; 
                                }
                                .slide-content { 
                                  font-size: 16px; 
                                  line-height: 1.6; 
                                  color: #666; 
                                  white-space: pre-wrap; 
                                }
                                .slide-number { 
                                  background: #1890ff; 
                                  color: white; 
                                  padding: 4px 8px; 
                                  border-radius: 4px; 
                                  font-size: 12px; 
                                  display: inline-block; 
                                  margin-bottom: 10px; 
                                }
                                .metadata { 
                                  background: #e6f7ff; 
                                  padding: 15px; 
                                  border-radius: 8px; 
                                  margin-bottom: 20px; 
                                }
                              </style>
                            </head>
                            <body>
                              <h1>📊 Presentación</h1>
                              <div class="metadata">
                                <strong>Diapositivas:</strong> ${presentationData.slides?.length || 0}<br>
                                <strong>Creado:</strong> ${presentationData.metadata?.createdAt ? new Date(presentationData.metadata.createdAt).toLocaleString('es-ES') : 'No disponible'}<br>
                                <strong>Versión:</strong> ${presentationData.metadata?.version || 'No disponible'}
                              </div>
                              ${presentationData.slides?.map((slide, index) => `
                                <div class="slide" style="background-color: ${slide.backgroundColor || '#ffffff'}; color: ${slide.textColor || '#333333'};">
                                  <div class="slide-number">Diapositiva ${index + 1}</div>
                                  <div class="slide-title" style="font-family: ${slide.fontFamily || 'Arial, sans-serif'}; text-align: ${slide.alignment || 'left'};">${slide.title || 'Sin título'}</div>
                                  <div class="slide-content" style="font-family: ${slide.fontFamily || 'Arial, sans-serif'}; font-size: ${slide.fontSize || 16}px; text-align: ${slide.alignment || 'left'};">${slide.content || ''}</div>
                                  ${slide.notes ? `<div style="margin-top: 15px; padding: 10px; background: #fff3cd; border-radius: 4px; font-size: 14px;"><strong>Notas:</strong> ${slide.notes}</div>` : ''}
                                </div>
                              `).join('') || '<p>No hay diapositivas disponibles</p>'}
                            </body>
                          </html>
                        `);
                        newWindow.document.close();
                      }
                    }}
                    style={{ marginRight: 8 }}
                  >
                    Ver Presentación ({presentationData.slides?.length || 0} diapositivas)
                  </Button>
                  <div style={{ fontSize: '12px', color: '#666', marginTop: 4 }}>
                    📊 Presentación interactiva • {presentationData.slides?.length || 0} diapositivas
                  </div>
                </div>
              );
            } catch (error) {
              console.error('Error parsing presentation content:', error);
              return (
                <div style={{ padding: 16, textAlign: 'center', color: '#ff4d4f' }}>
                  <div>Error al procesar presentación</div>
                  <div style={{ fontSize: '12px', marginTop: 4 }}>
                    El contenido no tiene formato válido de presentación
                  </div>
                </div>
              );
            }
          }
        };

        return (
          <div style={baseStyle}>
            <Text>📊 Presentación</Text>
            <div style={{ marginTop: 8 }}>
              {renderPresentationContent()}
            </div>
          </div>
        );

      case 'text':
      default:
        return (
          <div style={baseStyle}>
            <div style={{ whiteSpace: 'pre-wrap' }}>
              <Text>{note.content}</Text>
            </div>
            {note.driveFileId && (
              <div style={{ marginTop: 12, padding: 8, background: '#e6f7ff', borderRadius: 4 }}>
                <Space>
                  <PaperClipOutlined style={{ color: '#1890ff' }} />
                  <Text type="secondary">Archivo adjunto disponible</Text>
                  <Button 
                    type="link" 
                    size="small"
                    onClick={() => {
                      window.open(`https://plataforma.mundoworld.school/api/student-notes/${note.id}/stream`, '_blank');
                    }}
                  >
                    Ver archivo
                  </Button>
                </Space>
              </div>
            )}
          </div>
        );
    }
  };

  const columns = [
    {
      title: 'Título',
      dataIndex: 'title',
      key: 'title',
      render: (title: string, record: StudentNote) => (
        <Space>
          {getTypeIcon(record.type)}
          <span>{title}</span>
          {record.isFavorite && <HeartOutlined style={{ color: '#ff4d4f' }} />}
          {record.driveFileId && (
            <Tooltip title="Tiene archivo adjunto en Drive">
              <PaperClipOutlined style={{ color: '#52c41a' }} />
            </Tooltip>
          )}
        </Space>
      ),
    },
    {
      title: 'Tipo',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => (
        <Tag color={getTypeColor(type)}>{type.toUpperCase()}</Tag>
      ),
    },
    {
      title: 'Autor',
      dataIndex: 'author',
      key: 'author',
      render: (author: StudentNote['author']) => (
        <Space>
          <UserOutlined />
          <span>{formatUserName(author)}</span>
        </Space>
      ),
    },
    {
      title: 'Materia',
      dataIndex: 'subject',
      key: 'subject',
      render: (subject?: StudentNote['subject']) => (
        subject ? <Tag>{subject.name}</Tag> : <Text type="secondary">Sin materia</Text>
      ),
    },
    {
      title: 'Creado',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => dayjs(date).format('DD/MM/YYYY HH:mm'),
      sorter: true,
    },
    {
      title: 'Vistas',
      dataIndex: 'viewCount',
      key: 'viewCount',
      render: (count: number) => (
        <Badge count={count} overflowCount={999} />
      ),
    },
    {
      title: 'Acciones',
      key: 'actions',
      render: (_, record: StudentNote) => (
        <Space>
          <Button
            size="small"
            icon={<EyeOutlined />}
            onClick={() => handleViewNote(record)}
          >
            Ver
          </Button>
          <Popconfirm
            title="¿Eliminar este apunte?"
            description="Esta acción no se puede deshacer. Se eliminará el apunte y todos sus archivos asociados."
            onConfirm={() => handleDeleteNote(record.id)}
            okText="Eliminar"
            cancelText="Cancelar"
            okType="danger"
          >
            <Button
              size="small"
              danger
              icon={<DeleteOutlined />}
              loading={forceDeleteNoteMutation.isPending}
            >
              Eliminar
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  const renderOverviewTab = () => {
    if (statsLoading) return <Spin size="large" />;
    if (!dashboardStats || !dashboardStats.data) return null;

    const { overview, notesByType, topUsers } = dashboardStats.data;

    return (
      <div>
        <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Total de Apuntes"
                value={overview.totalNotes}
                prefix={<BookOutlined />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Usuarios Activos"
                value={overview.totalUsers}
                prefix={<UserOutlined />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Apuntes Hoy"
                value={overview.activeNotesToday}
                prefix={<CalendarOutlined />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Con Archivos"
                value={overview.notesWithAttachments}
                prefix={<Badge dot />}
              />
            </Card>
          </Col>
        </Row>

        <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Favoritos"
                value={overview.favoriteNotesCount}
                prefix={<HeartOutlined style={{ color: '#ff4d4f' }} />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Compartidos Total"
                value={overview.totalShared}
                prefix={<ShareAltOutlined />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Compartidos Activos"
                value={overview.activeShares}
                prefix={<ShareAltOutlined style={{ color: '#52c41a' }} />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} md={8} lg={6}>
            <Card>
              <Statistic
                title="Usuarios Únicos"
                value={overview.uniqueSharedWith}
                prefix={<UserOutlined />}
              />
            </Card>
          </Col>
        </Row>

        <Row gutter={[16, 16]}>
          <Col xs={24} md={12}>
            <Card title="Distribución por Tipo" bordered={false}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {Object.entries(notesByType).map(([type, count]) => (
                  <div key={type} style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Tag color={getTypeColor(type)}>{getTypeIcon(type)} {type.toUpperCase()}</Tag>
                    <Progress 
                      percent={Math.round((count / overview.totalNotes) * 100)} 
                      format={() => count}
                      style={{ flex: 1 }}
                    />
                  </div>
                ))}
              </div>
            </Card>
          </Col>
          <Col xs={24} md={12}>
            <Card title="Usuarios Más Activos" bordered={false}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {topUsers.slice(0, 8).map((user, index) => (
                  <div key={user.userId} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Space>
                      <Badge count={index + 1} />
                      <Text>{user.fullName || user.email}</Text>
                    </Space>
                    <Tag color="blue">{user.noteCount} apuntes</Tag>
                  </div>
                ))}
              </div>
            </Card>
          </Col>
        </Row>
      </div>
    );
  };

  const renderNotesTab = () => {
    return (
      <div>
        {/* Filters */}
        <Card style={{ marginBottom: 16 }}>
          <Row gutter={[16, 16]} align="middle">
            <Col xs={24} sm={12} md={6}>
              <Input
                placeholder="Buscar apuntes..."
                value={notesFilters.search}
                onChange={(e) => handleUpdateFilters('search', e.target.value)}
                allowClear
              />
            </Col>
            <Col xs={24} sm={12} md={4}>
              <Select
                placeholder="Tipo"
                value={notesFilters.type || undefined}
                onChange={(value) => handleUpdateFilters('type', value)}
                allowClear
                style={{ width: '100%' }}
              >
                <Option value="text">Texto</Option>
                <Option value="voice">Audio</Option>
                <Option value="drawing">Dibujo</Option>
                <Option value="mixed">Mixto</Option>
              </Select>
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Select
                placeholder="Ordenar por"
                value={`${notesFilters.sortBy}_${notesFilters.sortOrder}`}
                onChange={(value) => {
                  const [sortBy, sortOrder] = value.split('_');
                  handleUpdateFilters('sortBy', sortBy);
                  handleUpdateFilters('sortOrder', sortOrder);
                }}
                style={{ width: '100%' }}
              >
                <Option value="createdAt_DESC">Más recientes</Option>
                <Option value="createdAt_ASC">Más antiguos</Option>
                <Option value="viewCount_DESC">Más vistas</Option>
                <Option value="title_ASC">Título A-Z</Option>
              </Select>
            </Col>
            <Col xs={24} sm={12} md={2}>
              <Button 
                type="primary" 
                icon={<DownloadOutlined />}
                onClick={() => {
                  if (!notesData?.data?.data || notesData.data.data.length === 0) {
                    message.warning('No hay notas para exportar');
                    return;
                  }
                  
                  const notesForExport = notesData.data.data.map((note: StudentNote) => ({
                    titulo: note.title,
                    tipo: note.type,
                    estudiante: note.user?.email || 'N/A',
                    fechaCreacion: dayjs(note.createdAt).format('DD/MM/YYYY'),
                    vistas: note.viewCount,
                    favorito: note.isFavorite ? 'Sí' : 'No',
                    tieneArchivo: note.driveFileId ? 'Sí' : 'No'
                  }));
                  
                  exportToCSV(notesForExport, 'listado-apuntes-estudiantes');
                  message.success('Listado de apuntes exportado correctamente');
                }}
                block
              >
                Exportar
              </Button>
            </Col>
          </Row>
        </Card>

        {/* Notes Table */}
        <Card>
          <Table
            columns={columns}
            dataSource={notesData?.data?.data}
            rowKey="id"
            loading={notesLoading}
            pagination={{
              current: notesFilters.page,
              pageSize: notesFilters.limit,
              total: notesData?.data?.total || 0,
              showSizeChanger: true,
              showQuickJumper: true,
              showTotal: (total, range) => 
                `${range[0]}-${range[1]} de ${total} apuntes`,
              onChange: (page, pageSize) => {
                setNotesFilters(prev => ({
                  ...prev,
                  page: page,
                  limit: pageSize || prev.limit
                }));
              },
            }}
          />
        </Card>
      </div>
    );
  };

  const renderAnalyticsTab = () => {
    if (analyticsLoading) return <Spin size="large" />;
    if (!analyticsData || !analyticsData.data) return null;

    const analytics = analyticsData.data;

    // Datos REALES para gráfico de línea de actividad desde backend
    const activityData = analytics.timeline?.map((item: any) => ({
      date: dayjs(item.date).format('YYYY-MM-DD'),
      notes: parseInt(item.count) || 0
    })) || [];

    // Datos para gráfico de columnas por tipo
    const typeData = analytics.contentTypes?.map((content: any) => ({
      type: content.type.toUpperCase(),
      count: content.count,
      views: content.averageViews
    })) || [];

    // Datos para gráfico circular de tipos
    const pieData = analytics.contentTypes?.map((content: any) => ({
      type: content.type.toUpperCase(),
      value: content.count
    })) || [];

    const activityConfig = {
      data: activityData,
      xField: 'date',
      yField: 'notes',
      smooth: true,
      point: {
        size: 4,
        shape: 'circle',
      },
      color: '#1890ff',
      height: 200,
    };

    const columnConfig = {
      data: typeData,
      xField: 'type',
      yField: 'count',
      color: '#52c41a',
      height: 200,
    };

    const pieConfig = {
      data: pieData,
      angleField: 'value',
      colorField: 'type',
      radius: 0.8,
      height: 200,
      legend: {
        position: 'bottom' as const,
      },
    };

    return (
      <div>
        {/* Selector de período */}
        <Card style={{ marginBottom: 16 }}>
          <Row gutter={[16, 16]} align="middle">
            <Col>
              <Text strong>Período de análisis:</Text>
            </Col>
            <Col>
              <Select
                value={analyticsPeriod}
                onChange={setAnalyticsPeriod}
                style={{ width: 120 }}
              >
                <Select.Option value="week">Semana</Select.Option>
                <Select.Option value="month">Mes</Select.Option>
                <Select.Option value="year">Año</Select.Option>
              </Select>
            </Col>
            <Col>
              <Space>
                <Button 
                  type="primary" 
                  icon={<DownloadOutlined />}
                  onClick={() => {
                    exportAnalyticsToPDF(analytics, analyticsPeriod);
                    message.success('Reporte PDF generado correctamente');
                  }}
                >
                  Exportar PDF
                </Button>
                <Button 
                  icon={<DownloadOutlined />}
                  onClick={() => {
                    const csvData = [
                      // Datos de engagement
                      { 
                        metric: 'Promedio de Vistas', 
                        value: analytics.engagement.averageViews,
                        period: analyticsPeriod 
                      },
                      { 
                        metric: 'Tasa de Favoritos', 
                        value: `${analytics.engagement.favoriteRate}%`,
                        period: analyticsPeriod 
                      },
                      { 
                        metric: 'Máximo de Vistas', 
                        value: analytics.engagement.maxViews,
                        period: analyticsPeriod 
                      },
                      { 
                        metric: 'Total de Apuntes', 
                        value: analytics.engagement.totalNotes,
                        period: analyticsPeriod 
                      },
                    ];
                    exportToCSV(csvData, `analytics-apuntes-${analyticsPeriod}`);
                    message.success('Datos CSV exportados correctamente');
                  }}
                >
                  Exportar CSV
                </Button>
              </Space>
            </Col>
          </Row>
        </Card>

        {/* Estadísticas principales */}
        <Card title={`Analytics - ${analytics.period}`} style={{ marginBottom: 16 }}>
          <Row gutter={[16, 16]}>
            <Col xs={24} md={6}>
              <Statistic
                title="Promedio de Vistas"
                value={analytics.engagement.averageViews}
                precision={1}
                prefix={<EyeOutlined />}
              />
            </Col>
            <Col xs={24} md={6}>
              <Statistic
                title="Tasa de Favoritos"
                value={analytics.engagement.favoriteRate}
                precision={1}
                suffix="%"
                prefix={<HeartOutlined />}
              />
            </Col>
            <Col xs={24} md={6}>
              <Statistic
                title="Máximo de Vistas"
                value={analytics.engagement.maxViews}
                prefix={<BarChartOutlined />}
              />
            </Col>
            <Col xs={24} md={6}>
              <Statistic
                title="Total del Período"
                value={analytics.engagement.totalNotes}
                prefix={<BookOutlined />}
              />
            </Col>
          </Row>
        </Card>

        {/* Gráficos */}
        <Row gutter={[16, 16]} style={{ marginBottom: 16 }}>
          <Col xs={24} lg={12}>
            <Card title="Actividad Diaria" size="small">
              <Line {...activityConfig} />
            </Card>
          </Col>
          <Col xs={24} lg={12}>
            <Card title="Apuntes por Tipo" size="small">
              <Column {...columnConfig} />
            </Card>
          </Col>
        </Row>

        {/* Datos detallados */}
        <Row gutter={[16, 16]}>
          <Col xs={24} md={8}>
            <Card title="Usuarios Más Productivos" size="small">
              {analytics.topUsers?.map((user: any, index: number) => (
                <div key={user.userId} style={{ 
                  display: 'flex', 
                  justifyContent: 'space-between', 
                  alignItems: 'center',
                  padding: '8px 0',
                  borderBottom: index < analytics.topUsers.length - 1 ? '1px solid #f0f0f0' : 'none'
                }}>
                  <Space>
                    <Badge count={index + 1} />
                    <Text>{user.name}</Text>
                  </Space>
                  <Tag color="blue">{user.noteCount}</Tag>
                </div>
              ))}
            </Card>
          </Col>
          <Col xs={24} md={8}>
            <Card title="Tipos de Contenido" size="small">
              {analytics.contentTypes?.map((content: any) => (
                <div key={content.type} style={{ 
                  display: 'flex', 
                  justifyContent: 'space-between', 
                  alignItems: 'center',
                  padding: '8px 0'
                }}>
                  <Space>
                    {getTypeIcon(content.type)}
                    <Text>{content.type.toUpperCase()}</Text>
                  </Space>
                  <Space>
                    <Text>{content.count} apuntes</Text>
                    <Text type="secondary">({content.averageViews.toFixed(1)} vistas promedio)</Text>
                  </Space>
                </div>
              ))}
            </Card>
          </Col>
          <Col xs={24} md={8}>
            <Card title="Distribución por Tipo" size="small">
              <Pie {...pieConfig} />
            </Card>
          </Col>
        </Row>
      </div>
    );
  };

  const renderModerationTab = () => {
    if (moderationStatsLoading || reportsLoading) {
      return (
        <div style={{ textAlign: 'center', padding: '50px' }}>
          <Spin size="large" />
          <div style={{ marginTop: 16 }}>Cargando datos de moderación...</div>
        </div>
      );
    }

    return (
      <div>
        {/* Estadísticas de Moderación */}
        <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
          <Col xs={24} sm={12} lg={6}>
            <Card>
              <Statistic
                title="Total Reportes"
                value={moderationStats?.totalReports || 0}
                prefix={<SecurityScanOutlined style={{ color: '#1890ff' }} />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <Card>
              <Statistic
                title="Pendientes"
                value={moderationStats?.pendingReports || 0}
                prefix={<WarningOutlined style={{ color: '#faad14' }} />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <Card>
              <Statistic
                title="Resueltos"
                value={moderationStats?.resolvedReports || 0}
                prefix={<CheckCircleOutlined style={{ color: '#52c41a' }} />}
              />
            </Card>
          </Col>
          <Col xs={24} sm={12} lg={6}>
            <Card>
              <Statistic
                title="Tiempo Promedio (hrs)"
                value={moderationStats?.averageResolutionTime || 0}
                prefix={<CalendarOutlined style={{ color: '#722ed1' }} />}
              />
            </Card>
          </Col>
        </Row>

        {/* Acciones Rápidas */}
        <Card title="🛠️ Acciones Rápidas" style={{ marginBottom: 24 }}>
          <Space wrap>
            <Button 
              icon={<SettingOutlined />} 
              onClick={() => setShowConfigModal(true)}
            >
              Configurar Auto-Moderación
            </Button>
            <Button 
              icon={<SyncOutlined />} 
              loading={scanContentMutation.isPending}
              onClick={() => scanContentMutation.mutate()}
            >
              Escanear Contenido Existente
            </Button>
            <Button 
              icon={<DownloadOutlined />}
              onClick={() => {
                if (moderationReports?.data) {
                  exportToCSV(
                    moderationReports.data.map(report => ({
                      ID: report.id,
                      Nota: report.note.title,
                      Razón: getReasonLabel(report.reason),
                      Estado: report.status,
                      Prioridad: report.priority,
                      'Fecha Creación': dayjs(report.createdAt).format('DD/MM/YYYY HH:mm'),
                      'Reportado Por': report.reportedBy?.email || 'Sistema',
                    })),
                    'reportes-moderacion'
                  );
                }
              }}
            >
              Exportar Reportes
            </Button>
          </Space>
        </Card>

        {/* Filtros de Reportes */}
        <Card title="🔍 Filtros de Reportes" style={{ marginBottom: 24 }}>
          <Row gutter={[16, 16]}>
            <Col xs={24} sm={12} md={6}>
              <Select
                placeholder="Estado"
                style={{ width: '100%' }}
                value={moderationFilters.status || undefined}
                onChange={(value) => handleUpdateModerationFilters('status', value || '')}
                allowClear
              >
                <Select.Option value="pending">Pendiente</Select.Option>
                <Select.Option value="approved">Aprobado</Select.Option>
                <Select.Option value="rejected">Rechazado</Select.Option>
                <Select.Option value="flagged">Flagged</Select.Option>
              </Select>
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Select
                placeholder="Razón"
                style={{ width: '100%' }}
                value={moderationFilters.reason || undefined}
                onChange={(value) => handleUpdateModerationFilters('reason', value || '')}
                allowClear
              >
                <Select.Option value="inappropriate_content">Contenido Inapropiado</Select.Option>
                <Select.Option value="spam">Spam</Select.Option>
                <Select.Option value="harassment">Acoso</Select.Option>
                <Select.Option value="violence">Violencia</Select.Option>
                <Select.Option value="adult_content">Contenido Adulto</Select.Option>
                <Select.Option value="copyright">Derechos de Autor</Select.Option>
                <Select.Option value="fake_news">Noticias Falsas</Select.Option>
                <Select.Option value="other">Otro</Select.Option>
              </Select>
            </Col>
            <Col xs={24} sm={12} md={6}>
              <DatePicker.RangePicker
                style={{ width: '100%' }}
                onChange={(dates) => {
                  if (dates && dates[0] && dates[1]) {
                    handleUpdateModerationFilters('dateFrom', dates[0].format('YYYY-MM-DD'));
                    handleUpdateModerationFilters('dateTo', dates[1].format('YYYY-MM-DD'));
                  } else {
                    handleUpdateModerationFilters('dateFrom', '');
                    handleUpdateModerationFilters('dateTo', '');
                  }
                }}
              />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Button 
                onClick={() => {
                  setModerationFilters({
                    page: 1,
                    limit: 20,
                    status: '',
                    reason: '',
                    moderatorId: '',
                    dateFrom: '',
                    dateTo: '',
                  });
                }}
              >
                Limpiar Filtros
              </Button>
            </Col>
          </Row>
        </Card>

        {/* Lista de Reportes */}
        <Card title="📋 Lista de Reportes de Moderación">
          <Table
            columns={[
              {
                title: 'Prioridad',
                dataIndex: 'priority',
                key: 'priority',
                width: 90,
                render: (priority: number) => (
                  <Badge 
                    color={getPriorityColor(priority)} 
                    text={`P${priority}`}
                  />
                ),
                sorter: true,
              },
              {
                title: 'Estado',
                dataIndex: 'status',
                key: 'status',
                width: 100,
                render: (status: string) => (
                  <Tag color={getStatusColor(status)} icon={getStatusIcon(status)}>
                    {status.toUpperCase()}
                  </Tag>
                ),
              },
              {
                title: 'Razón',
                dataIndex: 'reason',
                key: 'reason',
                width: 150,
                render: (reason: string) => getReasonLabel(reason),
              },
              {
                title: 'Tipo',
                key: 'reportType',
                width: 100,
                render: (_, record: ModerationReport) => (
                  <Tag color={record.commentId ? 'blue' : 'green'} icon={record.commentId ? <MessageOutlined /> : <FileTextOutlined />}>
                    {record.commentId ? 'Comentario' : 'Nota'}
                  </Tag>
                ),
              },
              {
                title: 'Contenido Reportado',
                key: 'content',
                render: (_, record: ModerationReport) => {
                  if (record.commentId && (record.comment || record.metadata?.commentContent)) {
                    // Es un reporte de comentario
                    return (
                      <div>
                        <div style={{ fontWeight: 'bold', color: '#1890ff' }}>
                          💬 Comentario reportado
                        </div>
                        <div style={{ color: '#666', fontSize: '12px', marginBottom: 4 }}>
                          Por: {record.comment?.user?.profile?.firstName || 'Usuario'} {record.comment?.user?.profile?.lastName || ''}
                          {record.metadata?.commentAuthorEmail && !record.comment && (
                            <span> ({record.metadata.commentAuthorEmail})</span>
                          )}
                        </div>
                        <div style={{ color: '#999', fontSize: '11px' }}>
                          En nota: "{record.note.title}" de {formatUserName(record.note.author)}
                        </div>
                      </div>
                    );
                  } else {
                    // Es un reporte de nota completa
                    return (
                      <div>
                        <div style={{ fontWeight: 'bold', color: '#52c41a' }}>
                          {getTypeIcon(record.note.type)} {record.note.title}
                        </div>
                        <div style={{ color: '#666', fontSize: '12px' }}>
                          Por: {formatUserName(record.note.author)}
                        </div>
                      </div>
                    );
                  }
                },
              },
              {
                title: 'Reportado Por',
                dataIndex: 'reportedBy',
                key: 'reportedBy',
                width: 150,
                render: (reportedBy: any) => reportedBy?.email || 'Sistema',
              },
              {
                title: 'Fecha',
                dataIndex: 'createdAt',
                key: 'createdAt',
                width: 120,
                render: (date: string) => dayjs(date).format('DD/MM/YYYY HH:mm'),
                sorter: true,
              },
              {
                title: 'Acciones',
                key: 'actions',
                width: 150,
                render: (_, record: ModerationReport) => (
                  <Space size="small">
                    <Tooltip title="Ver Detalles">
                      <Button
                        type="link"
                        size="small"
                        icon={<EyeOutlined />}
                        onClick={() => handleViewReport(record)}
                      />
                    </Tooltip>
                    <Tooltip title="Tomar Acción">
                      <Button
                        type="link"
                        size="small"
                        icon={<SettingOutlined />}
                        onClick={() => handleTakeAction(record)}
                      />
                    </Tooltip>
                  </Space>
                ),
              },
            ]}
            dataSource={moderationReports?.data || []}
            rowKey="id"
            loading={reportsLoading}
            pagination={{
              current: moderationFilters.page,
              pageSize: moderationFilters.limit,
              total: moderationReports?.total || 0,
              showSizeChanger: true,
              showQuickJumper: true,
              showTotal: (total) => `Total ${total} reportes`,
              onChange: (page, pageSize) => {
                handleUpdateModerationFilters('page', page);
                handleUpdateModerationFilters('limit', pageSize);
              },
            }}
          />
        </Card>
      </div>
    );
  };

  const renderSettingsTab = () => {
    return (
      <div>
        {/* Configuración Básica */}
        <Card title="📋 Configuración Básica" style={{ marginBottom: 16 }}>
          <Row gutter={[16, 16]}>
            <Col xs={24} md={12}>
              <div style={{ marginBottom: 16 }}>
                <Text strong>Tamaño máximo de archivo (MB):</Text>
                <Input
                  type="number"
                  value={systemSettings.maxFileSize}
                  onChange={(e) => setSystemSettings(prev => ({
                    ...prev,
                    maxFileSize: Number(e.target.value)
                  }))}
                  style={{ marginTop: 8 }}
                  placeholder="20"
                />
                <Text type="secondary" style={{ fontSize: '12px', display: 'block', marginTop: 4 }}>
                  Tamaño máximo permitido para archivos de audio, imagen y otros adjuntos
                </Text>
              </div>
              
              <div style={{ marginBottom: 16 }}>
                <Text strong>Máximo de apuntes por usuario:</Text>
                <Input
                  type="number"
                  value={systemSettings.maxNotesPerUser}
                  onChange={(e) => setSystemSettings(prev => ({
                    ...prev,
                    maxNotesPerUser: Number(e.target.value)
                  }))}
                  style={{ marginTop: 8 }}
                  placeholder="1000"
                />
                <Text type="secondary" style={{ fontSize: '12px', display: 'block', marginTop: 4 }}>
                  Límite de apuntes que cada estudiante puede crear
                </Text>
              </div>
            </Col>
            <Col xs={24} md={12}>
              <div style={{ marginBottom: 16 }}>
                <Text strong>Eliminar automáticamente después de (días):</Text>
                <Input
                  type="number"
                  placeholder="Dejar vacío para no eliminar"
                  value={systemSettings.autoDeleteAfterDays || ''}
                  onChange={(e) => setSystemSettings(prev => ({
                    ...prev,
                    autoDeleteAfterDays: e.target.value ? Number(e.target.value) : null
                  }))}
                  style={{ marginTop: 8 }}
                />
                <Text type="secondary" style={{ fontSize: '12px', display: 'block', marginTop: 4 }}>
                  Eliminación automática de apuntes antiguos (opcional)
                </Text>
              </div>

              <div style={{ marginBottom: 16 }}>
                <Text strong>Habilitar compartición de apuntes:</Text>
                <div style={{ marginTop: 8 }}>
                  <Select
                    value={systemSettings.enableSharing ? 'enabled' : 'disabled'}
                    onChange={(value) => setSystemSettings(prev => ({
                      ...prev,
                      enableSharing: value === 'enabled'
                    }))}
                    style={{ width: '100%' }}
                  >
                    <Select.Option value="enabled">✅ Permitir</Select.Option>
                    <Select.Option value="disabled">❌ Prohibir</Select.Option>
                  </Select>
                </div>
                <Text type="secondary" style={{ fontSize: '12px', display: 'block', marginTop: 4 }}>
                  Permite a estudiantes compartir apuntes entre compañeros
                </Text>
              </div>
            </Col>
          </Row>
        </Card>

        {/* Tipos de Archivo Permitidos */}
        <Card title="📎 Tipos de Archivo Permitidos" style={{ marginBottom: 16 }}>
          <div style={{ marginBottom: 16 }}>
            <Text strong>Formatos permitidos para archivos adjuntos:</Text>
            <div style={{ marginTop: 8 }}>
              <Select
                mode="multiple"
                placeholder="Seleccionar tipos de archivo permitidos"
                value={systemSettings.allowedFileTypes || ['image/*', 'audio/*']}
                onChange={(value) => setSystemSettings(prev => ({
                  ...prev,
                  allowedFileTypes: value
                }))}
                style={{ width: '100%' }}
              >
                <Select.Option value="image/*">🖼️ Imágenes (JPG, PNG, GIF)</Select.Option>
                <Select.Option value="audio/*">🎵 Audio (MP3, WAV, M4A)</Select.Option>
                <Select.Option value="video/*">🎥 Video (MP4, MOV, AVI)</Select.Option>
                <Select.Option value="application/pdf">📄 PDF</Select.Option>
                <Select.Option value="text/plain">📃 Texto plano (TXT)</Select.Option>
              </Select>
            </div>
            <Text type="secondary" style={{ fontSize: '12px', display: 'block', marginTop: 4 }}>
              Los estudiantes solo podrán subir archivos de los tipos seleccionados
            </Text>
          </div>
        </Card>

        {/* Acciones */}
        <Card title="⚙️ Acciones del Sistema">
          <Space>
            <Button 
              type="primary" 
              icon={<SettingOutlined />}
              loading={updateSettingsMutation.isPending}
              onClick={handleSaveSettings}
            >
              Guardar Configuración
            </Button>
            <Button 
              icon={<DeleteOutlined />}
              onClick={() => {
                message.info('Función de limpieza masiva próximamente');
              }}
            >
              Limpieza Masiva
            </Button>
            <Button 
              icon={<DownloadOutlined />}
              onClick={() => {
                const configData = [
                  { setting: 'Tamaño máximo de archivo (MB)', value: systemSettings.maxFileSize },
                  { setting: 'Máximo de apuntes por usuario', value: systemSettings.maxNotesPerUser },
                  { setting: 'Eliminar automáticamente después de (días)', value: systemSettings.autoDeleteAfterDays || 'No configurado' },
                  { setting: 'Compartición habilitada', value: systemSettings.enableSharing ? 'Sí' : 'No' },
                  { setting: 'Tipos de archivo permitidos', value: (systemSettings.allowedFileTypes || []).join(', ') }
                ];
                exportToCSV(configData, 'configuracion-apuntes');
                message.success('Configuración exportada a CSV');
              }}
            >
              Exportar Config
            </Button>
          </Space>
        </Card>
      </div>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div style={{ padding: '24px' }}>
        <Title level={2}>
          <BookOutlined /> Administración de Apuntes de Estudiantes
        </Title>

        <Tabs 
          activeKey={activeTab} 
          onChange={(key) => setActiveTab(key as any)}
          items={[
            {
              key: 'overview',
              label: (
                <span>
                  <BarChartOutlined />
                  Resumen
                </span>
              ),
              children: renderOverviewTab(),
            },
            {
              key: 'notes',
              label: (
                <span>
                  <BookOutlined />
                  Todos los Apuntes
                </span>
              ),
              children: renderNotesTab(),
            },
            {
              key: 'analytics',
              label: (
                <span>
                  <BarChartOutlined />
                  Analytics
                </span>
              ),
              children: renderAnalyticsTab(),
            },
            {
              key: 'moderation',
              label: (
                <span>
                  <SecurityScanOutlined />
                  Moderación
                </span>
              ),
              children: renderModerationTab(),
            },
            {
              key: 'settings',
              label: (
                <span>
                  <SettingOutlined />
                  Configuración
                </span>
              ),
              children: renderSettingsTab(),
            },
          ]}
        />

        {/* Note Detail Modal */}
        <Modal
          title={selectedNote ? `Detalles del Apunte: ${selectedNote.title}` : ''}
          open={showNoteModal}
          onCancel={() => setShowNoteModal(false)}
          footer={[
            <Button key="close" onClick={() => setShowNoteModal(false)}>
              Cerrar
            </Button>,
            <Popconfirm
              key="delete"
              title="¿Eliminar este apunte?"
              description="Esta acción no se puede deshacer."
              onConfirm={() => selectedNote && handleDeleteNote(selectedNote.id)}
              okText="Eliminar"
              cancelText="Cancelar"
              okType="danger"
            >
              <Button 
                danger 
                icon={<DeleteOutlined />}
                loading={forceDeleteNoteMutation.isPending}
              >
                Eliminar
              </Button>
            </Popconfirm>,
          ]}
          width={800}
        >
          {selectedNote && (
            <div>
              <Row gutter={[16, 16]}>
                <Col xs={24} sm={12}>
                  <Text strong>Autor: </Text>
                  <Text>{formatUserName(selectedNote.author)}</Text>
                </Col>
                <Col xs={24} sm={12}>
                  <Text strong>Tipo: </Text>
                  <Tag color={getTypeColor(selectedNote.type)}>
                    {getTypeIcon(selectedNote.type)} {selectedNote.type.toUpperCase()}
                  </Tag>
                </Col>
                <Col xs={24} sm={12}>
                  <Text strong>Creado: </Text>
                  <Text>{dayjs(selectedNote.createdAt).format('DD/MM/YYYY HH:mm')}</Text>
                </Col>
                <Col xs={24} sm={12}>
                  <Text strong>Vistas: </Text>
                  <Badge count={selectedNote.viewCount} />
                </Col>
                {selectedNote.subject && (
                  <Col xs={24} sm={12}>
                    <Text strong>Materia: </Text>
                    <Tag>{selectedNote.subject.name}</Tag>
                  </Col>
                )}
              </Row>
              
              <Divider />
              
              <div>
                <Text strong>Contenido:</Text>
                {renderNoteContent(selectedNote)}
              </div>
            </div>
          )}
        </Modal>

        {/* Moderation Action Modal */}
        <Modal
          title="Acción de Moderación"
          open={showActionModal}
          onOk={handleModerationAction}
          onCancel={() => setShowActionModal(false)}
          confirmLoading={takeModerationActionMutation.isPending}
        >
          {selectedReport && (
            <div>
              <p><strong>Reporte:</strong> {selectedReport.id}</p>
              <p><strong>Razón:</strong> {formatModerationReason(selectedReport.reason)}</p>
              {selectedReport.description && (
                <p><strong>Descripción:</strong> {selectedReport.description}</p>
              )}
              
              <Form form={moderationForm} layout="vertical">
                <Form.Item 
                  name="action" 
                  label="Acción" 
                  rules={[{ required: true, message: 'Selecciona una acción' }]}
                >
                  <Select placeholder="Selecciona una acción">
                    <Select.Option value="approve">Aprobar</Select.Option>
                    <Select.Option value="reject">Rechazar</Select.Option>
                    <Select.Option value="flag">Marcar</Select.Option>
                    <Select.Option value="delete">Eliminar</Select.Option>
                    <Select.Option value="warn_user">Advertir Usuario</Select.Option>
                  </Select>
                </Form.Item>
                
              </Form>
            </div>
          )}
        </Modal>

        {/* Moderation Configuration Modal */}
        <Modal
          title="Configuración de Moderación"
          open={showConfigModal}
          onOk={handleModerationConfigSave}
          onCancel={() => setShowConfigModal(false)}
          confirmLoading={updateModerationConfigMutation.isPending}
          width={900}
        >
          <Form form={moderationConfigForm} layout="vertical">
            {/* Azure AI Content Safety Section */}
            <Card 
              title="Azure AI Content Safety" 
              size="small" 
              style={{ marginBottom: 16 }}
              extra={
                <Button 
                  size="small" 
                  onClick={handleTestAzureConnection}
                  loading={testingAzureConnection}
                >
                  Probar Conexión
                </Button>
              }
            >
              <Row gutter={16}>
                <Col xs={24} md={12}>
                  <Form.Item 
                    name="autoModerationEnabled" 
                    valuePropName="checked"
                  >
                    <Checkbox>Activar Auto-moderación con Azure AI Content Safety</Checkbox>
                  </Form.Item>
                </Col>
                <Col xs={24} md={12}>
                  <Form.Item>
                    <span style={{ fontSize: '12px', color: '#666' }}>
                      Estado: {azureStatus ? (
                        <Tag color={azureStatus.isConfigured && azureStatus.isWorking ? 'green' : 'red'}>
                          {azureStatus.isConfigured && azureStatus.isWorking ? 'Conectado' : 'Desconectado'}
                        </Tag>
                      ) : (
                        <Tag color="default">Sin verificar</Tag>
                      )}
                    </span>
                    {azureStatus?.error && (
                      <div style={{ fontSize: '11px', color: '#ff4d4f', marginTop: 4 }}>
                        {azureStatus.error}
                      </div>
                    )}
                  </Form.Item>
                </Col>
              </Row>
              
              <Alert
                message="Configuración de Azure AI Content Safety"
                description={
                  <div>
                    <p>Para usar Azure AI Content Safety (reemplazo de Content Moderator), configura las siguientes variables de entorno en el servidor:</p>
                    <code style={{ display: 'block', background: '#f6f8fa', padding: '8px', margin: '8px 0', borderRadius: '4px' }}>
                      AZURE_CONTENT_SAFETY_KEY=tu-clave-de-azure<br/>
                      AZURE_CONTENT_SAFETY_ENDPOINT=https://tu-resource-name.cognitiveservices.azure.com/
                    </code>
                    <p>Obtén estas credenciales desde el portal de Azure AI Services. Azure Content Moderator fue deprecado y reemplazado por AI Content Safety.</p>
                  </div>
                }
                type="info"
                showIcon
                style={{ marginTop: 8 }}
              />
            </Card>

            {/* Basic Configuration */}
            <Card title="Configuración Básica" size="small" style={{ marginBottom: 16 }}>
              <Row gutter={16}>
                <Col xs={24} md={12}>
                  <Form.Item 
                    name="autoApproveTrustedUsers" 
                    valuePropName="checked"
                  >
                    <Checkbox>Auto-aprobar usuarios de confianza</Checkbox>
                  </Form.Item>
                </Col>
                <Col xs={24} md={12}>
                  <Form.Item 
                    name="sensitivity" 
                    label="Sensibilidad de Auto-moderación (1-10)"
                  >
                    <Slider min={1} max={10} marks={{ 1: 'Baja', 5: 'Media', 10: 'Alta' }} />
                  </Form.Item>
                </Col>
              </Row>
            </Card>

            {/* Content Filters */}
            <Card title="Filtros de Contenido" size="small" style={{ marginBottom: 16 }}>
              <Form.Item 
                name="bannedWords" 
                label="Palabras Prohibidas"
              >
                <Select
                  mode="tags"
                  placeholder="Añadir palabras prohibidas..."
                  style={{ width: '100%' }}
                />
              </Form.Item>
              
              <Form.Item 
                name="suspiciousPhrases" 
                label="Frases Sospechosas"
              >
                <Select
                  mode="tags"
                  placeholder="Añadir frases sospechosas..."
                  style={{ width: '100%' }}
                />
              </Form.Item>
            </Card>

            {/* Notification Settings */}
            <Card title="Notificaciones" size="small">
              <Row gutter={16}>
                <Col xs={24} md={8}>
                  <Form.Item 
                    name="notifyModeratorsOnReport" 
                    valuePropName="checked"
                  >
                    <Checkbox>Notificar moderadores en reportes</Checkbox>
                  </Form.Item>
                </Col>
                <Col xs={24} md={8}>
                  <Form.Item 
                    name="notifyUsersOnAction" 
                    valuePropName="checked"
                  >
                    <Checkbox>Notificar usuarios sobre acciones</Checkbox>
                  </Form.Item>
                </Col>
                <Col xs={24} md={8}>
                  <Form.Item 
                    name="maxModerationHours" 
                    label="Máximo de horas para moderación"
                  >
                    <InputNumber min={1} max={168} style={{ width: '100%' }} />
                  </Form.Item>
                </Col>
              </Row>
            </Card>
          </Form>
        </Modal>

        {/* Modal de Detalles del Reporte */}
        <Modal
          title="Detalles del Reporte"
          open={showReportModal}
          onCancel={() => setShowReportModal(false)}
          footer={[
            <Button key="close" onClick={() => setShowReportModal(false)}>
              Cerrar
            </Button>,
          ]}
          width={600}
        >
          {selectedReport && (
            <div>
              <Row gutter={[16, 16]}>
                <Col xs={24} md={12}>
                  <Text strong>ID del Reporte:</Text>
                  <div>{selectedReport.id}</div>
                </Col>
                <Col xs={24} md={12}>
                  <Text strong>Estado:</Text>
                  <div>
                    <Tag color={selectedReport.status === 'pending' ? 'gold' : selectedReport.status === 'approved' ? 'green' : 'red'}>
                      {selectedReport.status.charAt(0).toUpperCase() + selectedReport.status.slice(1)}
                    </Tag>
                  </div>
                </Col>
                <Col xs={24} md={12}>
                  <Text strong>Razón:</Text>
                  <div>{formatModerationReason(selectedReport.reason)}</div>
                </Col>
                <Col xs={24} md={12}>
                  <Text strong>Prioridad:</Text>
                  <div>
                    <Badge 
                      count={selectedReport.priority} 
                      style={{ 
                        backgroundColor: selectedReport.priority >= 4 ? '#f5222d' : 
                                        selectedReport.priority >= 3 ? '#fa8c16' : 
                                        selectedReport.priority >= 2 ? '#fadb14' : '#52c41a' 
                      }} 
                    />
                  </div>
                </Col>
                <Col xs={24}>
                  <Text strong>Descripción:</Text>
                  <div style={{ marginTop: 8, padding: 12, background: '#f5f5f5', borderRadius: 6 }}>
                    {selectedReport.description || 'Sin descripción'}
                  </div>
                </Col>
                <Col xs={24} md={12}>
                  <Text strong>Fecha del Reporte:</Text>
                  <div>{dayjs(selectedReport.createdAt).format('DD/MM/YYYY HH:mm')}</div>
                </Col>
                <Col xs={24} md={12}>
                  <Text strong>Reportado por:</Text>
                  <div>{selectedReport.reportedBy?.profile?.firstName} {selectedReport.reportedBy?.profile?.lastName}</div>
                </Col>
                {/* Mostrar contenido específico según el tipo de reporte */}
                {selectedReport.commentId && (selectedReport.comment || selectedReport.metadata?.commentContent) ? (
                  // Reporte de comentario específico
                  <>
                    <Col xs={24}>
                      <Divider>Comentario Reportado</Divider>
                    </Col>
                    <Col xs={24}>
                      <Text strong>Contenido del Comentario:</Text>
                      <div style={{ 
                        marginTop: 8, 
                        padding: 12, 
                        background: '#fff2f0', 
                        border: '1px solid #ffccc7',
                        borderRadius: 6, 
                        maxHeight: 200, 
                        overflow: 'auto' 
                      }}>
                        {selectedReport.comment?.content || selectedReport.metadata?.commentContent || 'Contenido no disponible'}
                      </div>
                    </Col>
                    <Col xs={24} md={12}>
                      <Text strong>Autor del Comentario:</Text>
                      <div>
                        {selectedReport.comment?.user?.profile?.firstName || 'Usuario'} {selectedReport.comment?.user?.profile?.lastName || ''} 
                        {selectedReport.metadata?.commentAuthorEmail && (
                          <span style={{ color: '#666', fontSize: '12px' }}>
                            {' '}({selectedReport.metadata.commentAuthorEmail})
                          </span>
                        )}
                      </div>
                    </Col>
                    <Col xs={24} md={12}>
                      <Text strong>Fecha del Comentario:</Text>
                      <div>{selectedReport.comment?.createdAt ? dayjs(selectedReport.comment.createdAt).format('DD/MM/YYYY HH:mm') : 'No disponible'}</div>
                    </Col>
                    {selectedReport.note && (
                      <>
                        <Col xs={24}>
                          <Divider>Contexto - Nota Padre</Divider>
                        </Col>
                        <Col xs={24}>
                          <Text strong>Título de la Nota:</Text>
                          <div>{selectedReport.note.title}</div>
                        </Col>
                        <Col xs={24}>
                          <Text strong>Contenido de la Nota:</Text>
                          <div style={{ 
                            marginTop: 8, 
                            padding: 12, 
                            background: '#f6ffed', 
                            border: '1px solid #b7eb8f',
                            borderRadius: 6, 
                            maxHeight: 150, 
                            overflow: 'auto' 
                          }}>
                            {selectedReport.note.content}
                          </div>
                        </Col>
                        <Col xs={24} md={12}>
                          <Text strong>Autor de la Nota:</Text>
                          <div>{selectedReport.note.author?.profile?.firstName} {selectedReport.note.author?.profile?.lastName}</div>
                        </Col>
                      </>
                    )}
                  </>
                ) : selectedReport.note ? (
                  // Reporte de nota completa
                  <>
                    <Col xs={24}>
                      <Divider>Nota Reportada</Divider>
                    </Col>
                    <Col xs={24}>
                      <Text strong>Título:</Text>
                      <div>{selectedReport.note.title}</div>
                    </Col>
                    <Col xs={24}>
                      <Text strong>Contenido:</Text>
                      <div style={{ 
                        marginTop: 8, 
                        padding: 12, 
                        background: '#fff2f0', 
                        border: '1px solid #ffccc7',
                        borderRadius: 6, 
                        maxHeight: 200, 
                        overflow: 'auto' 
                      }}>
                        {selectedReport.note.content}
                      </div>
                    </Col>
                    <Col xs={24} md={12}>
                      <Text strong>Autor:</Text>
                      <div>{selectedReport.note.author?.profile?.firstName} {selectedReport.note.author?.profile?.lastName}</div>
                    </Col>
                    <Col xs={24} md={12}>
                      <Text strong>Fecha de Creación:</Text>
                      <div>{dayjs(selectedReport.note.createdAt).format('DD/MM/YYYY HH:mm')}</div>
                    </Col>
                  </>
                ) : null}
              </Row>
            </div>
          )}
        </Modal>
      </div>
    </motion.div>
  );
};

export default AdminStudentNotesPage;